import type { DefineSchema } from '../../../src'
import { NButton } from 'naive-ui'
import { h, reactive, ref } from 'vue'
import {
  cascaderOptions,
  cityOptions,
  departmentTree,
  mentionOptions,
  roleOptions,
  tagOptions,
  transferOptions,
} from './options'

export const componentsModel = reactive({
  input: 'Naive Schema Form',
  textarea: '多行文本内容',
  autoComplete: '',
  select: null,
  cascader: null,
  treeSelect: null,
  checkbox: true,
  checkboxGroup: ['important'],
  radio: false,
  radioGroup: 'operator',
  date: null,
  datetime: null,
  dateRange: null,
  dateTimeRange: null,
  time: null,
  inputNumber: 12,
  switchValue: true,
  color: '#18a058',
  rate: 3,
  slider: 36,
  dynamicInput: ['第一项', '第二项'],
  dynamicTags: ['Vue', 'Naive UI'],
  mention: '',
  transfer: ['read'],
  files: [],
})

export const componentsSchema = ref<DefineSchema<typeof componentsModel>[]>([
  {
    field: 'input',
    label: 'Input',
    component: 'input',
    placeholder: '请输入文本',
    componentProps: { clearable: true },
    gridItemProps: { span: 8 },
  },
  {
    field: 'textarea',
    label: 'Textarea',
    component: 'input',
    componentProps: { type: 'textarea', rows: 3 },
    gridItemProps: { span: 8 },
  },
  {
    field: 'autoComplete',
    label: 'AutoComplete',
    component: 'autoComplete',
    options: cityOptions,
    gridItemProps: { span: 8 },
  },
  {
    field: 'select',
    label: 'Select',
    component: 'select',
    options: roleOptions,
    componentProps: { clearable: true, filterable: true },
    gridItemProps: { span: 8 },
  },
  {
    field: 'cascader',
    label: 'Cascader',
    component: 'cascader',
    options: cascaderOptions,
    componentProps: { clearable: true },
    gridItemProps: { span: 8 },
  },
  {
    field: 'treeSelect',
    label: 'TreeSelect',
    component: 'treeSelect',
    options: departmentTree,
    componentProps: { keyField: 'key', clearable: true },
    gridItemProps: { span: 8 },
  },
  {
    field: 'checkbox',
    label: 'Checkbox',
    component: 'checkbox',
    componentSlots: '单个开关项',
    gridItemProps: { span: 8 },
  },
  {
    field: 'checkboxGroup',
    label: 'CheckboxGroup',
    component: 'checkboxGroup',
    options: tagOptions,
    gridItemProps: { span: 8 },
  },
  {
    field: 'radio',
    label: 'Radio',
    component: 'radio',
    componentSlots: '单选布尔项',
    gridItemProps: { span: 8 },
  },
  {
    field: 'radioGroup',
    label: 'RadioGroup',
    component: 'radioGroup',
    options: roleOptions,
    gridItemProps: { span: 8 },
  },
  {
    field: 'date',
    label: 'Date',
    component: 'datePicker',
    componentProps: { type: 'date', clearable: true },
    gridItemProps: { span: 8 },
  },
  {
    field: 'datetime',
    label: 'Datetime',
    component: 'datePicker',
    componentProps: { type: 'datetime', clearable: true },
    gridItemProps: { span: 8 },
  },
  {
    field: 'dateRange',
    label: 'DateRange',
    component: 'datePicker',
    componentProps: { type: 'daterange', clearable: true },
    startPlaceholder: '开始日期',
    endPlaceholder: '结束日期',
    gridItemProps: { span: 8 },
  },
  {
    field: 'dateTimeRange',
    label: 'DateTimeRange',
    component: 'datePicker',
    componentProps: { type: 'datetimerange', clearable: true },
    startPlaceholder: '开始时间',
    endPlaceholder: '结束时间',
    gridItemProps: { span: 8 },
  },
  {
    field: 'time',
    label: 'TimePicker',
    component: 'timePicker',
    componentProps: { clearable: true },
    gridItemProps: { span: 8 },
  },
  {
    field: 'inputNumber',
    label: 'InputNumber',
    component: 'inputNumber',
    componentProps: { min: 0, max: 100, step: 2 },
    gridItemProps: { span: 8 },
  },
  {
    field: 'switchValue',
    label: 'Switch',
    component: 'switch',
    gridItemProps: { span: 8 },
  },
  {
    field: 'color',
    label: 'ColorPicker',
    component: 'colorPicker',
    gridItemProps: { span: 8 },
  },
  {
    field: 'rate',
    label: 'Rate',
    component: 'rate',
    componentProps: { allowHalf: true },
    gridItemProps: { span: 8 },
  },
  {
    field: 'slider',
    label: 'Slider',
    component: 'slider',
    componentProps: { min: 0, max: 100, marks: { 0: '0', 50: '50', 100: '100' } },
    gridItemProps: { span: 8 },
  },
  {
    field: 'dynamicInput',
    label: 'DynamicInput',
    component: 'dynamicInput',
    componentProps: { min: 1, max: 5 },
    gridItemProps: { span: 12 },
  },
  {
    field: 'dynamicTags',
    label: 'DynamicTags',
    component: 'dynamicTags',
    gridItemProps: { span: 12 },
  },
  {
    field: 'mention',
    label: 'Mention',
    component: 'mention',
    options: mentionOptions,
    placeholder: '输入 @ 试试',
    gridItemProps: { span: 12 },
  },
  {
    field: 'transfer',
    label: 'Transfer',
    component: 'transfer',
    options: transferOptions,
    gridItemProps: { span: 12 },
  },
  {
    field: 'files',
    label: 'Upload',
    component: 'upload',
    modelProp: 'fileList',
    componentProps: { defaultUpload: false, multiple: true, max: 3 },
    componentSlots: h(NButton, null, { default: () => '选择文件' }),
    gridItemProps: { span: 24 },
  },
])
